---
language: 'perl'
perl:
  - '5.22'
  - '5.20'
  - '5.18'
env:
  - TEST_AUTHOR=1 PERL_CPANM_OPT="--notest --force --skip-satisfied"
before_install:
  # get the perl modules we need
  # install dist development dependencies
  - "cpanm Dist::Zilla"
  - "dzil authordeps | xargs cpanm"
  - "export tmpbuild=`mktemp --directory`"
  - "dzil build --in $tmpbuild"
install: "dzil listdeps | xargs cpanm"
script: "dzil test --author"
notifications:
  email:
    on_failure: always
    on_success: change
