---
language: 'perl'
perl:
  - '5.30'
  - '5.32'
  - '5.34'
  - '5.36'
env:
  - TEST_AUTHOR=1 PERL_CPANM_OPT="--notest --force --skip-satisfied"
before_install:
  # get the perl modules we need
  #
  # install dist development dependencies
  - "cpanm Dist::Zilla"
  - "dzil authordeps | grep '::' | xargs cpanm"
  - "export tmpbuild=`mktemp --directory`"
  - "dzil build --in $tmpbuild"
  # for reporting to coveralls.io
  - "cpanm --quiet --notest Devel::Cover::Report::Coveralls"  
install: "dzil listdeps | xargs cpanm"
script:
  - "dzil test --author"
  - PERL5OPT=-MDevel::Cover=-coverage,statement,branch,condition,path,subroutine prove -lrsv t  
  - cover
after_success:
  - cover -report coveralls 
notifications:
  email:
    on_failure: always
    on_success: change
